### ISSUE TITLE
Missing styles.css

### ISSUE THREAD

**Issue by m-escher** [TatuLund/ViewPortExtension#3]
The referenced styles.css file seems to be missing hence the following error:
"Requested resource [/VAADIN/widgetsets/de.adito.aditoweb.vaadin.widget.AditoVaadinWidgetSet/viewportextension/styles.css] not found from filesystem or through class loader. Add widgetset and/or theme JAR to your classpath or add files to WebContent/VAADIN folder."

**Comment by TatuLund** [comment]
I seem to have missed that filed when commiting, I added the file.
